config/routes.rb
Rails.application.routes.draw do

  delete '/backlogs/:id', to: 'purchase_entries#releaseBacklog', as: 'release_backlog'

  get '/create_user', to: 'users#newUser', as: 'create_user'
  post '/create_user', to: 'users#createUser'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/history', to: 'histories#index', as: 'history'
  root "sessions#new"
  post '/login', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#newPurchasing', as: 'signup'
  post '/signup', to: 'users#createPurchasing', as: 'create_purchasing_user'


  get 'products/:id/release_form', to: 'products#releaseForm', as: 'release_product_form'
  patch 'products/:id/release', to: 'products#release', as: 'release_product'
  get 'products/:id/create_entry_form', to: 'purchase_entries#createEntryForm', as: 'create_entry_form'
  post '/create_entry/:id', to: 'purchase_entries#createEntry', as: 'create_entry'
  get '/create_backlog_form/:id', to: 'purchase_entries#backlogForm', as: 'backlog_form'
  post '/create_backlog/:id', to: 'purchase_entries#backlog', as: 'create_backlog'
  get "/backlogs", to: "purchase_entries#showBacklogs", as: "backlogs"
  get 'year_end', to: 'products#yearEnd', as: 'year_end'
  resources :purchase_entries
  resources :purchase_orders

  # actions show,index,new,create,delete,update,edit
  resources :products do
    member do
      get 'add_form', to: 'products#addForm', as: 'add_quantity_form'
      patch 'add', to: 'products#add', as: 'add_quantity'
    end
    collection do
      get 'search', to: 'products#brandQuery', as: 'brand_query'
    end
  end

  get 'year_end_report_csv', to: 'products#getYearEndCSV'
end

app/models/purchase_entry.rb
class PurchaseEntry < ApplicationRecord
  belongs_to :product
  belongs_to :purchase_order
end

app/controllers/purchase_entries_controller.rb
class PurchaseEntriesController < ApplicationController
  before_action :set_purchase_entry, only: [:show, :edit, :update, :destroy]

  def releaseBacklog
    @purchase_entry = PurchaseEntry.find_by(product_id: params[:id])
    newQty =@purchase_entry.product.quantity - @purchase_entry.product_qty
    if newQty > 0
      @purchase_entry.product.quantity = newQty
      @purchase_entry.product.save
      @purchase_entry.delete
    else
      flash["danger"] = "You currently do not have enough quantity of the product."
    end
    redirect_to backlogs_path
  end

  def newEntryToOrder
    #
  end
  def createEntryToOrder
    #
  end

  # status legend
  # 0 - unconfirmed
  # 1 - confirmed
  # 2 - backlogged

  def backlogForm
    @product = Product.find(params[:id])
    @purchase_entry = PurchaseEntry.new()
    @purchase_orders = PurchaseOrder.all
  end

  def backlog
    @product = Product.find(params[:id])
    @purchase_entry = PurchaseEntry.new(purchase_entry_params)
    @purchase_entry.status = PurchaseEntriesHelper::BACKLOGGED
    @purchase_entry.product_id = @product.id
    respond_to do |format|
      if @purchase_entry.save
        format.html { redirect_to @purchase_entry, notice: 'Purchase entry was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_entry }
      else
        format.html { render :new }
        format.json { render json: @purchase_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def createEntryForm
    @product = Product.find(params[:id])
    @purchase_orders = PurchaseOrder.all
    @purchase_entry = PurchaseEntry.new()
  end

  def createEntry
    @product = Product.find(params[:id])
    @purchase_entry = PurchaseEntry.new(purchase_entry_params)
    @purchase_entry.product_id = @product.id
    case @purchase_entry.status
    when "Unconfirmed"
      @purchase_entry.status = PurchaseEntriesHelper::UNCONFIRMED
    when "Confirmed"
      @purchase_entry.status = PurchaseEntriesHelper::CONFIRMED
    when "Backlogged"
      @purchase_entry.status = PurchaseEntriesHelper::BACKLOGGED
    end
    @products = Product.all
    respond_to do |format|
      if @purchase_entry.save
        format.html { redirect_to @purchase_entry, notice: 'Purchase entry was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_entry }
      else
        format.html { render :new }
        format.json { render json: @purchase_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def showBacklogs
    @purchase_entries = PurchaseEntry.where(status: PurchaseEntriesHelper::BACKLOGGED)
    render "backlogs"
  end
  # GET /purchase_entries
  # GET /purchase_entries.json
  def index
    @purchase_entries = PurchaseEntry.all
  end

  # GET /purchase_entries/1
  # GET /purchase_entries/1.json
  def show
  end

  # GET /purchase_entries/new
  def new
    @purchase_entry = PurchaseEntry.new
    @products = Product.all
  end

  # GET /purchase_entries/1/edit
  def edit
  end

  # POST /purchase_entries
  # POST /purchase_entries.json
  def create
    @purchase_entry = PurchaseEntry.new(purchase_entry_params)

    respond_to do |format|
      if @purchase_entry.save
        format.html { redirect_to @purchase_entry, notice: 'Purchase entry was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_entry }
      else
        format.html { render :new }
        format.json { render json: @purchase_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_entries/1
  # PATCH/PUT /purchase_entries/1.json
  def update
    respond_to do |format|
      if @purchase_entry.update(purchase_entry_params)
        format.html { redirect_to @purchase_entry, notice: 'Purchase entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_entry }
      else
        format.html { render :edit }
        format.json { render json: @purchase_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_entries/1
  # DELETE /purchase_entries/1.json
  def destroy
    @purchase_entry.destroy
    respond_to do |format|
      format.html { redirect_to purchase_entries_url, notice: 'Purchase entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_entry
      @purchase_entry = PurchaseEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_entry_params
      params.require(:purchase_entry).permit(:product_name, :product_qty, :status, :product_id, :purchase_order_id, :brand)
    end
end

app/helpers/purchase_entries_helper.rb
module PurchaseEntriesHelper
  # status legend
  # 0 - unconfirmed
  # 1 - confirmed
  # 2 - backlogged
  # global class-enumeration for purchase entries status
  UNCONFIRMED=0
  CONFIRMED=1
  BACKLOGGED=2
end

app/views/purchase_entries/_form.html.erb
<%= form_with(model: purchase_entry, local: true) do |form| %>
  <% if purchase_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_entry.errors.count, "error") %> prohibited this purchase_entry from being saved:</h2>

      <ul>
      <% purchase_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id, value: "Product ID" %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :product_qty %>
    <%= form.number_field :product_qty %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, [["CONFIRMED", PurchaseEntriesHelper::CONFIRMED],["UNCONFIRMED", PurchaseEntriesHelper::UNCONFIRMED],["BACKLOGGED", PurchaseEntriesHelper::BACKLOGGED]] %>
  </div>

  <div class="field">
    <%= form.label :purchase_order_id, value: "Inventory Request ID"%>
    <%= form.text_field :purchase_order_id  %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_entries/backlogForm.html.erb
<div class="container row">
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container">
      <div class="card-title">
        <h2>Product Details</h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-5 font-weight-bold">Product ID</div>
          <div class="col-md"><%= @product.id %></div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">Brand</div>
          <div class="col-md"><%= @product.brand %></div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Product Type
          </div>
          <div class="col-md">
            <%= @product.product_type %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Current Quantity
          </div>
          <div class="col-md">
            <%= @product.quantity %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container">
      <h2 class="card-title">Backlog Product</h2>
      <div class="card-body">
        <%= form_for @purchase_entry, url: create_backlog_path(@product.id), class: :form, method: :post do |form| %>
        <% if @purchase_entry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@purchase_entry.errors.count, "error") %> prohibited this purchase entry from being saved:</h2>
          <ul>
            <% @purchase_entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="field">
          <%= form.label :product_qty %>
          <%= form.number_field :product_qty %>
        </div>
        <div class="field">
          <%= form.label :purchase_order_id, value: "Purchase Order ID" %>
          <%= form.number_field :purchase_order_id %>
        </div>
        <div class="actions">
          <%= form.submit 'Create Purchase Entry', class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<h2>List of Purchase Orders</h2>
<%= render 'purchase_orders/list_purchase_orders' %>

app/views/purchase_entries/backlogs.html.erb
<p id="notice"><%= notice %></p>

<h1>Backlogged Purchase Entries</h1>
<%= render 'layouts/flashes' %>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Product ID / SKU</th>
      <th>Product qty</th>
      <th>PO Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_entries.each do |purchase_entry| %>
      <tr>
        <td><%= purchase_entry.product.brand %></td>
        <td><%= purchase_entry.product.id %></td>
        <td><%= purchase_entry.product_qty %></td>
        <td><%= purchase_entry.purchase_order_id %></td>
        <td><%= link_to 'Release', release_backlog_path(purchase_entry.product.id), method: :delete, class: "text-success" %></td>
        <td><%= link_to 'Edit', edit_purchase_entry_path(purchase_entry), class: "text-warning" %></td>
        <td><%= link_to 'Delete', purchase_entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/purchase_entries/createEntryForm.html.erb
<div class="container row">
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container">
      <div class="card-title">
        <h2>Product Details</h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-5 font-weight-bold">Product ID</div>
          <div class="col-md"><%= @product.id %></div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">Brand</div>
          <div class="col-md"><%= @product.brand %></div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Product Type
          </div>
          <div class="col-md">
            <%= @product.product_type %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Current Quantity
          </div>
          <div class="col-md">
            <%= @product.quantity %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container">
      <h2 class="card-title">Create Purchase Entry</h2>
      <div class="card-body">
        <%= form_for @purchase_entry, url: create_entry_path(@product.id), class: :form, method: :post do |form| %>
        <% if @purchase_entry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@purchase_entry.errors.count, "error") %> prohibited this purchase entry from being saved:</h2>
          <ul>
            <% @purchase_entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="field">
          <%= form.label :product_qty %>
          <%= form.number_field :product_qty %>
        </div>

        <div class="field">
          <%= form.label :status %>
          <%= form.select :status, ['Unconfirmed', 'Confirmed', 'Backlogged'] %>
        </div>
        <div class="field">
          <%= form.label :purchase_order_id, value: "Inventory Request ID" %>
          <%= form.select :purchase_order_id, PurchaseOrder.ids %>
        </div>
        <div class="actions">
          <%= form.submit 'Create Purchase Entry', class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<h2>List of Inventory Requests</h2>
<%= render 'purchase_orders/list_purchase_orders' %>

app/views/purchase_entries/edit.html.erb
<h1>Editing Purchase Entry</h1>

<%= render 'form', purchase_entry: @purchase_entry %>

<%#= link_to 'Show', @purchase_entry %> 
<%#= link_to 'Back', purchase_entries_path %>

app/views/purchase_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchase Entries</h1>

<table class="table text-white table-dark table-striped">
  <thead>
    <tr>
      <th>SKU</th>
      <th>Product name</th>
      <th>Product qty</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_entries.each do |purchase_entry| %>
      <tr>
        <td><%= purchase_entry.product.id %></td>
        <td><%= purchase_entry.product.brand %></td>
        <td><%= purchase_entry.product_qty %></td>
        <td><%= purchase_entry.status %></td>
        <td><%= link_to 'Show', purchase_entry %></td>
        <td><%= link_to 'Edit', edit_purchase_entry_path(purchase_entry) %></td>
        <td><%= link_to 'Destroy', purchase_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase Entry', new_purchase_entry_path %>

app/views/purchase_entries/new.html.erb
<h1>New Purchase Entry</h1>

<%= render 'form', purchase_entry: @purchase_entry %>
<h3>List of Products Available</h3>
<table class="table text-white">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Product type</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.brand %></td>
        <td><%= product.product_type %></td>
        <td><%= product.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/purchase_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @purchase_entry.product_name %>
</p>

<p>
  <strong>Product qty:</strong>
  <%= @purchase_entry.product_qty %>
</p>

<p>
  <strong>Status:</strong>
  <%= @purchase_entry.status %>
</p>

<%= link_to 'Edit', edit_purchase_entry_path(@purchase_entry) %> |
<%= link_to 'Back', purchase_entries_path %>