config/routes.rb
Rails.application.routes.draw do

  delete '/backlogs/:id', to: 'purchase_entries#releaseBacklog', as: 'release_backlog'

  get '/create_user', to: 'users#newUser', as: 'create_user'
  post '/create_user', to: 'users#createUser'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/history', to: 'histories#index', as: 'history'
  root "sessions#new"
  post '/login', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#newPurchasing', as: 'signup'
  post '/signup', to: 'users#createPurchasing', as: 'create_purchasing_user'


  get 'products/:id/release_form', to: 'products#releaseForm', as: 'release_product_form'
  patch 'products/:id/release', to: 'products#release', as: 'release_product'
  get 'products/:id/create_entry_form', to: 'purchase_entries#createEntryForm', as: 'create_entry_form'
  post '/create_entry/:id', to: 'purchase_entries#createEntry', as: 'create_entry'
  get '/create_backlog_form/:id', to: 'purchase_entries#backlogForm', as: 'backlog_form'
  post '/create_backlog/:id', to: 'purchase_entries#backlog', as: 'create_backlog'
  get "/backlogs", to: "purchase_entries#showBacklogs", as: "backlogs"
  get 'year_end', to: 'products#yearEnd', as: 'year_end'
  resources :purchase_entries
  resources :purchase_orders

  # actions show,index,new,create,delete,update,edit
  resources :products do
    member do
      get 'add_form', to: 'products#addForm', as: 'add_quantity_form'
      patch 'add', to: 'products#add', as: 'add_quantity'
    end
    collection do
      get 'search', to: 'products#brandQuery', as: 'brand_query'
    end
  end

  get 'year_end_report_csv', to: 'products#getYearEndCSV'
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  has_many :purchase_entries
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: 'Purchase order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:date_order, :status)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order, local: true) do |form| %>
  <% if purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
      <% purchase_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_order %>
    <%= form.datetime_select :date_order %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/purchase_orders/_list_purchase_orders.html.erb
<% @purchase_orders.each do |purchase_order| %>
<div class="card bg-dark text-white" style="box-shadow: 0px 0px 20px 5px rgba(0, 0, 0, 0.2);">
  <div class="card-body bg-secondary">
    <h4 class="card-title">Inventory Request #<%= purchase_order.id %></h4>
      <% if (purchase_order.status.upcase == "UNCONFIRMED") %>
         <h5 class="text-danger">UNCONFIRMED</h5>
      <% end %>
      <% if (purchase_order.status.upcase == "CONFIRMED") %>
        <h5 class="text-success">CONFIRMED</h5>
      <% end %>
    <p>Created at <%= purchase_order.created_at %></p>
  </div>
  <div class="mb-4">

    <% if purchase_order.purchase_entries.length == 0 %>
      <h6 class="text-center">No entries in this purchase order!</h6>
    <% else %>
      <table class="table table-dark">
        <thead>
          <tr>
            <th>Brand</th>
            <th>Product ID / SKU</th>
            <th>Product qty</th>
            <th>Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% purchase_order.purchase_entries.each do |purchase_entry| %>
          <tr>
            <td><%= purchase_entry.product.brand %></td>
            <td><%= purchase_entry.product_id %></td>
            <td><%= purchase_entry.product_qty %></td>
            <td>
              <% if (purchase_entry.status == PurchaseEntriesHelper::UNCONFIRMED) %>
              <b class="text-danger">UNCONFIRMED</b>
              <% end %>
              <% if (purchase_entry.status == PurchaseEntriesHelper::CONFIRMED) %>
              <b class="text-success">CONFIRMED</b>
              <% end %>
              <% if (purchase_entry.status == PurchaseEntriesHelper::BACKLOGGED) %>
              <b class="text-warning">BACKLOGGED</b>
              <% end %>
            </td>
            <td><%= link_to 'Show', purchase_entry %></td>
            <td><%= link_to 'Edit', edit_purchase_entry_path(purchase_entry) %></td>
            <td><%= link_to 'Destroy', purchase_entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger"%></td>
            </tr>
            <% end %>
          </tbody>
      </table>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm">
        <button class="btn btn-primary"><%= link_to 'Show', purchase_order %></button>
      </div>
      <div class="col-sm">
        <button class="btn btn-info">  <%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></button>
      </div>
      <div class="col-sm">
        <button class="btn btn-danger"><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/purchase_orders/edit.html.erb
<h1>Editing Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

<div class="card bg-secondary text-white">
  <h4 class="card-title text-center">Involved Entries</h4>
  <div class="card-body ">
    <table class="table">
      <thead>
        <tr>
          <th>Product name</th>
          <th>Product ID / SKU</th>
          <th>Product qty</th>
          <th>PO Number</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @purchase_order.purchase_entries.each do |purchase_entry| %>
        <tr>
          <td><%= purchase_entry.product_name %></td>
          <td><%= purchase_entry.product_id %></td>
          <td><%= purchase_entry.product_qty %></td>
          <td><%= purchase_entry.purchase_order_id %></td>
          <td>
            <% if (purchase_entry.status == "0") %>
            <b class="text-danger">UNCONFIRMED</b>
            <% end %>
            <% if (purchase_entry.status == "1") %>
            <b class="text-success">CONFIRMED</b>
            <% end %></td>
            <td><%= link_to 'Show', purchase_entry %></td>
            <td><%= link_to 'Edit', edit_purchase_entry_path(purchase_entry), class: "btn btn-warning"%></td>
            <td><%= link_to 'Destroy', purchase_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
    <%# link_to 'New Entry', '#', class: 'btn btn-primary' %>
  </div>
</div>

app/views/purchase_orders/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-5">
    <h1>Inventory Requests</h1>
  </div>
  <div class="col-sm-7">
    <button class="btn btn-primary"><%= link_to 'Create Inventory Request', new_purchase_order_path %></button>
  </div>
</div>

<%= render 'list_purchase_orders' %>

app/views/purchase_orders/new.html.erb
<h1>New Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date order:</strong>
  <%= @purchase_order.date_order %>
</p>

<p>
  <strong>Status:</strong>
  <%= @purchase_order.status %>
</p>

<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>