config/routes.rb
Rails.application.routes.draw do

  delete '/backlogs/:id', to: 'purchase_entries#releaseBacklog', as: 'release_backlog'

  get '/create_user', to: 'users#newUser', as: 'create_user'
  post '/create_user', to: 'users#createUser'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/history', to: 'histories#index', as: 'history'
  root "sessions#new"
  post '/login', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#newPurchasing', as: 'signup'
  post '/signup', to: 'users#createPurchasing', as: 'create_purchasing_user'


  get 'products/:id/release_form', to: 'products#releaseForm', as: 'release_product_form'
  patch 'products/:id/release', to: 'products#release', as: 'release_product'
  get 'products/:id/create_entry_form', to: 'purchase_entries#createEntryForm', as: 'create_entry_form'
  post '/create_entry/:id', to: 'purchase_entries#createEntry', as: 'create_entry'
  get '/create_backlog_form/:id', to: 'purchase_entries#backlogForm', as: 'backlog_form'
  post '/create_backlog/:id', to: 'purchase_entries#backlog', as: 'create_backlog'
  get "/backlogs", to: "purchase_entries#showBacklogs", as: "backlogs"
  get 'year_end', to: 'products#yearEnd', as: 'year_end'
  resources :purchase_entries
  resources :purchase_orders

  # actions show,index,new,create,delete,update,edit
  resources :products do
    member do
      get 'add_form', to: 'products#addForm', as: 'add_quantity_form'
      patch 'add', to: 'products#add', as: 'add_quantity'
    end
    collection do
      get 'search', to: 'products#brandQuery', as: 'brand_query'
    end
  end

  get 'year_end_report_csv', to: 'products#getYearEndCSV'
end

app/models/product.rb
class Product < ApplicationRecord
  require 'csv'
  has_many :purchase_entries

  def self.to_csv
    CSV.generate do |csv|
      columns = %w(id brand product_type quantity)
      csv << columns.map(&:humanize)
      all.each do |p|
        csv << p.attributes.values_at(*columns)
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'csv'
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, only: [:getYearEndCSV, :yearEnd]

  def yearEnd
    @products = Product.all
  end

  def getYearEndCSV
    @products = Product.all
    send_data (Product.to_csv)
  end

  def addForm
    if logged_in?
      @product = Product.find(params[:id])
    else
      redirect_to logged_in?
    end
  end

  def add
    @product = Product.find(params[:id])
    @product.quantity = @product.quantity + params[:add_qty].to_i
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def releaseForm
    @product = Product.find(params[:id])
  end

  def release
    @product = Product.find(params[:id])
    newQty = @product.quantity - params[:released_qty].to_i
    if newQty > 0
      @product.quantity = newQty
    end
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def brandQuery
    if(params[:brand_query])
      @products = Product.where('brand LIKE ?', "%#{params[:brand_query]}%")
    else
      @products = Product.all
    end
    render 'index'
  end

  # GET /products
  # GET /products.json
  def index
    if logged_in?
      @products = Product.all
    else
      redirect_to root_url
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    if logged_in?
      @product = Product.new
    else
      redirect_to root_url
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:brand, :product_type, :quantity, :unit_price, :brand_query, :released_qty, :add_qty)
    end

    # Only allow logged in people -- callback method
    def require_logged_in
      if !logged_in?
        redirect_to root_url
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :product_type %>
    <%= form.text_field :product_type %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.number_field :unit_price, step: :any%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/addForm.html.erb
<div class="card bg-secondary text-white container">
  <div class="card-title">
    <h2>Item Details</h2>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-5 font-weight-bold">
        Brand
      </div>
      <div class="col-md">
        <%= @product.brand %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5 font-weight-bold">
        Product Type
      </div>
      <div class="col-md">
        <%= @product.product_type %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5 font-weight-bold">
        Current Quantity
      </div>
      <div class="col-md">
        <%= @product.quantity %>
      </div>
    </div>
    <div class="row">
      <%= form_for @product, url: add_quantity_product_path(@product), class: :form, method: :patch do |form| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= number_field_tag :add_qty %>
      </div>
      <div class="actions">
        <%= form.submit 'Add Quantity', class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mb-5">
  <h4>What are you searching for?</h4>
  <div class="row">
    <div class="col-lg-auto">
      <%= form_tag({controller: "products", action: "brandQuery"}, method: :get, class: :form) do |form| %>
        <input id="brand_query"ntype="text" name="brand_query" placeholder="Brand Name">
        <%= submit_tag 'Search', name: nil, class: "" %>
      <% end %>
    </div>
    <div class="col-sm">
      <button class="btn btn-primary"><%= link_to 'New Product', new_product_path %></button>
    </div>
  </div>
</div>
<table class="table text-white table-dark table-striped">
  <thead class="bg-dark">
    <tr>
      <th>Brand</th>
      <th>Product type</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th colspan="7">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.brand %></td>
        <td><%= product.product_type %></td>
        <td><%= product.quantity %></td>
        <td><%= product.unit_price %></td>
        <td><%= link_to 'PO', create_entry_form_path(product), class: "text-success" %></td>
        <td><%= link_to 'Add', add_quantity_form_product_path(product), class: "text-success" %></td>
        <td><%= link_to 'Release', release_product_form_path(product), class: "text-success" %></td>
        <td><%= link_to 'Backlog', backlog_form_path(product), class: "text-success" %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "text-warning"%></td>
        <td ><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<div class="container card bg-secondary text-white">
  <h1 class="card-title">New Product</h1>
  <div class="card-body">
    <%= render 'form', product: @product, class: :form %>

  </div>

</div>

app/views/products/releaseForm.html.erb
<div class="container row">
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container">
      <div class="card-title">
        <h2>Item Details</h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Brand
          </div>
          <div class="col-md">
            <%= @product.brand %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Product Type
          </div>
          <div class="col-md">
            <%= @product.product_type %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card bg-secondary text-white container ">
      <div class="card-title">
        <h2>Release Item</h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-5 font-weight-bold">
            Current quantity
          </div>
          <div class="col-auto">
            <%= @product.quantity %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5">
            Release Quantity
          </div>
          <div class="col-auto">

          </div>
          <%= form_for @product, url: release_product_path(@product), class: :form, method: :patch do |form| %>
            <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= number_field_tag :released_qty %>
            </div>
            <div class="actions">
              <%= form.submit 'Release', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @product.product_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Unit Price:</strong>
  <%= @product.unit_price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/yearEnd.html.erb
<p id="notice"><%= notice %></p>

<div class="card container bg-secondary">
  <h2 class="card-title text-center">CTK Year End Report</h2>
  <table class="table table-striped table-dark ">
    <thead class="">
      <tr>
        <th>Brand</th>
        <th>Product type</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.brand %></td>
        <td><%= product.product_type %></td>
        <td><%= product.quantity %></td>
        <td><%= product.unit_price %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "text-warning"%></td>
        <td ><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger"%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <h3 class="btn btn-primary"><%= link_to "Export to CSV", year_end_report_csv_path %></h3>
</div>