config/routes.rb
Rails.application.routes.draw do

  delete '/backlogs/:id', to: 'purchase_entries#releaseBacklog', as: 'release_backlog'

  get '/create_user', to: 'users#newUser', as: 'create_user'
  post '/create_user', to: 'users#createUser'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/history', to: 'histories#index', as: 'history'
  root "sessions#new"
  post '/login', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#newPurchasing', as: 'signup'
  post '/signup', to: 'users#createPurchasing', as: 'create_purchasing_user'


  get 'products/:id/release_form', to: 'products#releaseForm', as: 'release_product_form'
  patch 'products/:id/release', to: 'products#release', as: 'release_product'
  get 'products/:id/create_entry_form', to: 'purchase_entries#createEntryForm', as: 'create_entry_form'
  post '/create_entry/:id', to: 'purchase_entries#createEntry', as: 'create_entry'
  get '/create_backlog_form/:id', to: 'purchase_entries#backlogForm', as: 'backlog_form'
  post '/create_backlog/:id', to: 'purchase_entries#backlog', as: 'create_backlog'
  get "/backlogs", to: "purchase_entries#showBacklogs", as: "backlogs"
  get 'year_end', to: 'products#yearEnd', as: 'year_end'
  resources :purchase_entries
  resources :purchase_orders

  # actions show,index,new,create,delete,update,edit
  resources :products do
    member do
      get 'add_form', to: 'products#addForm', as: 'add_quantity_form'
      patch 'add', to: 'products#add', as: 'add_quantity'
    end
    collection do
      get 'search', to: 'products#brandQuery', as: 'brand_query'
    end
  end

  get 'year_end_report_csv', to: 'products#getYearEndCSV'
end

app/views/layouts/_flashes.html.erb
<% flash.each do |k,v|%>
  <p class="text-<%= k %> bg-warning"><%= v %></p>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar text-white d-flex flex-row-reverse">
  <h4 class="p-2">
    Hello, <%= current_user.username %>
  </h4>

  <%= link_to '#', user_path(current_user), class: "p-2" %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidenav text-white bg-dark">
  <div class="container">
    <h5>MAIN</h5>
    <ul>
      <% if current_user.rank == UsersHelper::ADMIN%>
        <li><%= link_to "Current Inventory", products_path %></li>
      <% end %>
      <li><%= link_to "Inventory Requests", purchase_orders_path %></li>
      <li><%= link_to "Year-End Reports", year_end_path %></li>
      <li><%= link_to "Backlogs", backlogs_path %></li>
    </ul>
    <h5>PEOPLE</h5>
    <ul>
      <li><%= link_to "Users", create_user_path %></li>
      <li><%= link_to "View History", history_path %></li>
    </ul>
    <h5>SYSTEM</h5>
    <ul>
      <li><%= link_to "Log out", logout_path, method: :delete %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>CTK Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <% if logged_in? %>
      <%= render 'layouts/sidebar' %>
    <% end %>
    <% if logged_in? %>
        <div class="shift_right">
        <%= render 'layouts/header' %>
    <% end %>

      <div class="container bg-dark text-white">
        <%= yield %>
      </div>

      <div class="container bg-white">
        <%= debug(params) if Rails.env.development? %>
      </div>

    <% if logged_in? %>
        </div>
    <% end %>
  </body>
</html>